### ISSUE TITLE
Was causing lag issues

### ISSUE THREAD

**Issue by rodney528** [wiggin77/codedox#32] opened 2023-04-01 20:43 UTC
Type: <b>Bug</b>

It was allowing me to still delete text but it would take forever to type out what I typed.

Extension version: 1.3.3
VS Code version: Code 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T10:02:16.981Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600G with Radeon Graphics          (12 x 3893)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.29GB (19.13GB free)|
|Process Argv|C:\\Users\\okmil\\Pictures\\Internet Downloaded\\Friday Night Funkin'\\Modding Stuff\\Source Code\\FNF-Imaginative-Engine --crash-reporter-id 6ebc8497-3402-4601-9d98-51c761580449|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
6233i204:30672705
vsctsb:30677850
pythonb192:30669360
azdwalk:30687957
pythonms35:30701012

```

</details>

**Comment by wiggin77** [comment] 2023-04-04 18:37
@RodneyAnImaginativePerson thanks for the report. What makes you think that lag issue is caused by Codedox?

**Comment by rodney528** [comment] 2023-04-04 18:53
Idk it just started to happen I never really figured out the cause of it.

**Comment by rodney528** [comment] 2023-04-04 18:54
Like everything would be fine at first but then it would slowly start to lag and other extensions would just stop working after a bit.

**Comment by wiggin77** [comment] 2023-04-04 20:22
@RodneyAnImaginativePerson what lead you to suspect Codedox was the root cause?

**Comment by rodney528** [comment] 2023-04-05 00:22
> @RodneyAnImaginativePerson what lead you to suspect Codedox was the root cause?  

VSC asked if I wanted to bisect (slowly turning extensions back on till the problem resumed). But now the problem is a different extension for some reason?

**Comment by wiggin77** [comment] 2023-04-05 13:48
Ok, thanks for looking into it.  I'll close this since it appears to be reproducible without Codedox enabled.  Feel free to re-open if needed.

**Closed as completed by wiggin77** 2023-04-05 13:48 UTC
Labels: triage
